### ISSUE TITLE
Maven repo?

### ISSUE THREAD

**Issue by brentvukmer** [matlux/jvm-breakglass#21]
Great project, thank you for making this available.  Is the JAR only on clojars.org?   I'd like to use it at work, where we proxy to Maven Central, but not clojars.

**Comment by matlux** [comment]
Thanks for the compliment. I'm not sure how it would play out with the transitive dependencies like me.raynes/fs 1.4.6 which aren't available on Maven Central either. I wouldn't be able to force them to move onto Maven Central. So I'm not sure what I can do...

Beside, I have had the same issue at work (we have to use Nexus). I understand it can be painful to deal with internal red tape within large companies just to get an artifact. Generally I was able to request the admin of the company's Maven proxy to add artifacts and their dependencies from other repos. So far it has never been an issue as long as I was able to justify the business use of the artifact. Their vetting process would have been the same (regardless of the repo). Nexus & Artifactory both support any number of Repos. A lot of artifacts do not come from Maven Central these days. Maven Central does not guarantee that all it's artifacts are safe. I would be surprised if your admin was claiming that being on Maven Central was a proof of guaranteed quality. It sounds like a poor way to manage security if you ask me.
